# Base configs
baseurl: "https://TeeheeTakes.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Street Photography"
subtitle: "See the world through my eyes!"
author: "TeeheeTakes"
header:
 title: "Photography"
 subtitle: "-"
footer:
 name: "Hello World"
 bio: "Doing Streets Photography."
 github: "-"
web_design: "AJ"
social_urls:
  facebook: "-"
  twitter: "-"
  instagram: "-"
  dribbble: "-"
  linkedin: "-"
  github: "-"
